---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: popopo
  labels:
    app: popopo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: popopo
  template:
    metadata:
      labels:
        app: popopo
    spec:
      containers:
        - name: popopo
          image: docker.io/phengbunath/popopo:2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080